# Generated by Django 5.0.6 on 2024-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_remove_icecream_icecream_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecreamstore',
            name='icecream',
        ),
        migrations.AddField(
            model_name='icecreamstore',
            name='icecreams',
            field=models.ManyToManyField(to='icecream.icecream'),
        ),
    ]
